apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: restaurant-frontend
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: restaurant-frontend
    spec:
      containers:
      - name: restaurant-frontend
        image: restaurant-frontend:v1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: restaurant-frontend