apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menuservice
  template:
    metadata:
      labels:
        app: menuservice
        version: v1.0.0
    spec:
      containers:
      - name: menuservice
        image: <image_server>/backend:1.0.0
        ports:
        - containerPort: 5000
----